databases:
  - name: bookmark
    databaseName: bookmark
    user: bookmark

services:
  - type: web
    name: bookmark
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookmark
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
